name: Discord Commit Notifier

on:
  pull_request:
    branches-ignore: 
      - 'main'
    
  workflow_dispatch:

jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD }}
          title: "New `pull request` on fronted"
          color: 0x213ac4
