name: Discord Commit Notifier

on:
  push:
    branches-ignore: 
      - 'main'
    

  workflow_dispatch:

jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secret.DISCORD }}
          title: "New commit on fronted"
